#!/usr/bin/env bash

YELLOW="\e[93m"
GREEN="\e[32m"
RED="\e[31m"
ENDCOLOR="\e[0m"

printMessage() {
   printf "${YELLOW}AppFlowy : $1${ENDCOLOR}\n"
}

printSuccess() {
   printf "${GREEN}AppFlowy : $1${ENDCOLOR}\n"
}

printError() {
   printf "${RED}AppFlowy : $1${ENDCOLOR}\n"
}

printMessage "Running local AppFlowy pre-commit hook."

#flutter format .
##https://gist.github.com/benmccallum/28e4f216d9d72f5965133e6c43aaff6e
limit=$(( 100 * 2**20 )) # 100MB, GitHub's hard limit for a single file

function file_too_large(){
	filename=$1
	filesize=$(( $2 / 2**20 ))

	cat <<HEREDOC

	File $filename is $filesize MB, which is larger than github's maximum
        file size (100 MB). We will not be able to push this file to GitHub.
	Commit aborted
HEREDOC

}

empty_tree=$( git hash-object -t tree /dev/null )
if git rev-parse --verify HEAD > /dev/null 2>&1
then
	against=HEAD
else
	against=$empty_tree
fi

oversized=0
while IFS= read -r -d '' file; do
	blob=$( git ls-files --stage -- "$file" | awk '{ print $2 }' )
	[ -n "$blob" ] || continue
	file_size=$( git cat-file -s "$blob" )
	if [ "$file_size" -gt  "$limit" ]; then
		file_too_large "$file" "$file_size"
		oversized=1
	fi
done < <( git diff-index --cached --name-only -z --diff-filter=ACMR $against )

[ "$oversized" -eq 0 ] || exit 1
