import 'package:appflowy/plugins/base/icon/icon_widget.dart';
import 'package:appflowy/shared/icon_emoji_picker/icon_picker.dart';
import 'package:appflowy/shared/icon_emoji_picker/recent_icons.dart';
import 'package:appflowy/shared/icon_emoji_picker/vivid_icons.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

import 'vivid_icon_test_support.dart';

// References are intentionally not generated by the scoped implementation.
// The main verification run should generate and review these three NEW PNGs,
// then run the normal comparison; do not replace existing picker references.
void main() {
  setUpAll(() async {
    RecentIcons.enable = false;
    await prepareVividIconTestAssets();
  });
  setUp(resetVividIconTestPacks);
  tearDownAll(() => RecentIcons.enable = true);

  for (final appearance in vividIconTestAppearances) {
    testWidgets('Vivid picker golden - $appearance', (tester) async {
      tester.view.physicalSize = const Size(720, 440);
      tester.view.devicePixelRatio = 1;
      addTearDown(tester.view.reset);
      await tester.pumpWidget(
        vividIconTestApp(
          appearance,
          RepaintBoundary(
            key: const ValueKey('vivid-picker-reference'),
            child: Builder(
              builder: (context) => ColoredBox(
                color: Theme.of(context).scaffoldBackgroundColor,
                child: SizedBox(
                  width: 720,
                  height: 440,
                  child: Row(
                    children: [
                      SizedBox(
                        width: 360,
                        child: vividIconTestPicker(),
                      ),
                      Expanded(
                        child: Padding(
                          padding: const EdgeInsets.all(16),
                          child: Column(
                            mainAxisAlignment: MainAxisAlignment.center,
                            crossAxisAlignment: CrossAxisAlignment.start,
                            children: [
                              Text('Vivid · 24 original illustrations',
                                  style:
                                      Theme.of(context).textTheme.titleSmall,),
                              const SizedBox(height: 20),
                              Wrap(
                                spacing: 10,
                                runSpacing: 14,
                                children: [
                                  for (final icon
                                      in appFlowyVividIconGroups.single.icons)
                                    IconWidget(
                                      size: 42,
                                      iconsData: IconsData(
                                          vividIconTestGroup, icon.name, null,),
                                    ),
                                ],
                              ),
                              const SizedBox(height: 20),
                              const Text(
                                  'Original AppFlowy artwork · transparent SVG',),
                            ],
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ),
      );
      await tester.pumpAndSettle();
      await tester.tap(vividIconStyleButton('Vivid'));
      // Keep the reference free of an incidental mouse/keyboard focus wash.
      FocusManager.instance.primaryFocus?.unfocus();
      await settleVividIconPictures(tester);
      expect(vividIconOption('home').hitTestable(), findsOneWidget);
      expect(vividIconOption('compass').hitTestable(), findsOneWidget);
      expect(tester.takeException(), isNull);
      await expectLater(
        find.byKey(const ValueKey('vivid-picker-reference')),
        matchesGoldenFile('goldens/vivid_icon_picker_$appearance.png'),
      );
      await disposeVividIconPicker(tester);
    });
  }
}
