// Receives scripts generated by production Dart builders on stdin. No copied
// find implementation: every search, move, clear and shortcut runs those scripts.
const assert = require('node:assert/strict');
const { text } = require('node:stream/consumers');
const { JSDOM } = require('jsdom');

async function main() {
  // A synchronous fd 0 read stalls Dart's Windows stdin pipe before close()
  // completes. Drain the stream asynchronously; the Dart deadline stays intact.
  const commands = JSON.parse(await text(process.stdin));
  const dom = new JSDOM(`<!doctype html><html><head>
  <style>.hidden { display: none; }</style></head><body>
  <p id="inline"><a href="#article" id="link">App<strong>Flowy</strong></a> says Hello <em>World</em>.</p>
  <p id="lower">app<span>flowy</span> says hello <b>world</b>.</p>
  <p>a.b aXb [literal]</p><p>Alpha alpha alphabet</p>
  <p>hello\n   <i>wide</i>\n  world</p>
  <p>for<span>mat</span>ted</p><p>different</p><p>paragraph</p>
  <p>0 100</p>
  <div hidden><b>ghost</b></div><div class="hidden"><span>ghost</span></div>
  <div style="visibility:hidden"><span>ghost</span></div>
  <div style="opacity:0"><span>ghost</span></div>
  <div aria-hidden="true"><span>ghost</span></div>
  <div data-appflowy-find-ui><b>ghost</b></div>
  <div data-appflowy-find-ignore>ghost</div><div role="search">ghost</div>
  <script>ghost</script><style>/* ghost */</style><noscript>ghost</noscript>
  <template>ghost</template><textarea>ghost</textarea>
  </body></html>`, { runScripts: 'outside-only', pretendToBeVisual: true });
  const window = dom.window;
  const document = window.document;
  const scrolled = [];
  // jsdom has no layout/compositor. Only scrolling is recorded, not searching.
  window.HTMLElement.prototype.scrollIntoView = function (options) {
    scrolled.push({ element: this, options });
  };
  const danger = document.createElement('pre');
  danger.style.whiteSpace = 'pre';
  danger.textContent = commands.danger;
  document.body.appendChild(danger);
  const link = document.getElementById('link');
  const strong = link.querySelector('strong');
  const originalText = strong.firstChild;
  const bodyBefore = document.body.innerHTML;
  let clicks = 0;
  link.addEventListener('click', event => { clicks++; event.preventDefault(); });

  function result(source, count, index, invalid = false) {
    const value = window.eval(source);
    assert.equal(value.count, count);
    assert.equal(value.index, index);
    assert.equal(Boolean(value.invalid), invalid);
    return value;
  }
  function find(name, count, index = count ? 1 : 0, invalid = false) {
    return result(commands.find[name], count, index, invalid);
  }
  function key(options) {
    const event = new window.KeyboardEvent('keydown', {
      bubbles: true, cancelable: true, key: 'f', ...options,
    });
    document.dispatchEvent(event);
    return event;
  }

  try {
    // The real scrollbar installer returns undefined; readiness must still be
    // the boolean returned by the LAST expression in the combined installation.
    assert.equal(window.eval(commands.install), true);
    assert.equal(window.__appflowyPreviewScrollbarRoot, document.documentElement);
    find('inline', 2);
    assert.equal(link, document.getElementById('link'));
    assert.equal(strong, link.querySelector('strong'));
    assert.equal(document.querySelectorAll('#inline .appflowy-find-current').length, 2);
    link.dispatchEvent(new window.MouseEvent('click', { bubbles: true }));
    assert.equal(clicks, 1);
    result(commands.next, 2, 2);
    assert.equal(document.querySelectorAll('#lower .appflowy-find-current').length, 2);
    result(commands.next, 2, 1);
    result(commands.previous, 2, 2);
    assert.ok(scrolled.length >= 4);
    assert.equal(window.eval(commands.clear), true);
    assert.equal(strong.firstChild, originalText);
    assert.equal(document.body.innerHTML, bodyBefore);

    find('inlineCase', 1);
    find('phrase', 2);
    find('spaces', 1);
    find('word', 1);
    // The escaped dangerous string also contains a.b, intentionally.
    find('literal', 2);
    find('regex', 3);
    find('case', 1);
    find('whole', 2);
    find('subword', 3);
    find('hidden', 0);
    find('boundary', 0);
    find('zero', 3);
    find('none', 0);
    result(commands.next, 0, 0);
    result(commands.previous, 0, 0);
    find('invalid', 0, 0, true);
    find('zeroWidth', 0);
    find('danger', 1);
    find('empty', 0);
    assert.equal(document.body.innerHTML, bodyBefore);
    assert.equal(strong.firstChild, originalText);

    // A quoted colour cannot break out into executable JavaScript either.
    assert.equal(window.eval(commands.reinstall), true);
    assert.equal(window.injected, undefined);
    find('inline', 2);
    window.eval(commands.clear);

    assert.equal(key({ ctrlKey: true }).defaultPrevented, false);
    const messages = [];
    window[commands.binding] = payload => messages.push(['binding', payload]);
    assert.equal(key({ ctrlKey: true }).defaultPrevented, true);
    assert.deepEqual(messages, [['binding', commands.handler]]);
    assert.equal(key({ ctrlKey: true, repeat: true }).defaultPrevented, true);
    assert.equal(messages.length, 1);
    // Reinstallation must never register a second shortcut listener.
    window.eval(commands.install);
    assert.equal(key({ metaKey: true }).defaultPrevented, true);
    assert.equal(messages.length, 2);
    for (const options of [
      { ctrlKey: true, shiftKey: true }, { ctrlKey: true, altKey: true },
      { ctrlKey: true, metaKey: true }, { ctrlKey: true, key: 'h' }, {},
    ]) assert.equal(key(options).defaultPrevented, false);
    assert.equal(messages.length, 2);
    delete window[commands.binding];
    window.flutter_inappwebview = { callHandler: name => messages.push(['channel', name]) };
    key({ ctrlKey: true });
    assert.deepEqual(messages.at(-1), ['channel', commands.handler]);

    const bulk = document.createElement('p');
    bulk.textContent = 'hit '.repeat(4500);
    document.body.appendChild(bulk);
    const bulkText = bulk.firstChild;
    find('cap', 4000);
    assert.equal(bulk.querySelectorAll('mark.appflowy-find').length, 4000);
    result(commands.previous, 4000, 4000);
    result(commands.next, 4000, 1);
    window.eval(commands.clear);
    assert.equal(bulk.firstChild, bulkText);
    assert.equal(bulk.childNodes.length, 1);
    bulk.remove();

    // Live page edits must not resurrect old marked text when find is cleared.
    find('inline', 2);
    strong.querySelector('mark').textContent = 'Updated';
    window.eval(commands.clear);
    assert.equal(strong.textContent, 'Updated');
    assert.equal(strong.firstChild, originalText);
    link.dispatchEvent(new window.MouseEvent('click', { bubbles: true }));
    assert.equal(clicks, 2);
    find('inline', 1);
    const liveElement = document.createElement('em');
    liveElement.textContent = 'Live update';
    let liveClicks = 0;
    liveElement.addEventListener('click', () => liveClicks++);
    document.querySelector('#lower .appflowy-find').replaceChildren(liveElement);
    window.eval(commands.clear);
    assert.equal(liveElement.isConnected, true);
    liveElement.dispatchEvent(new window.MouseEvent('click'));
    assert.equal(liveClicks, 1);
    console.log('Production DOM find, counts, navigation, escaping and native messages passed.');
  } finally {
    window.close();
  }
}

main().catch(error => {
  console.error(error);
  process.exitCode = 1;
});