import 'dart:typed_data';

import 'package:flutter/services.dart' show rootBundle;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import 'ashtakavarga.dart';
import 'astrology_date_analysis.dart';
import 'astrology_model.dart';
import 'astrology_panchanga.dart';
import 'astrology_time.dart';
import 'jaimini_karakas.dart';
import 'shadbala.dart';
import 'vedic_chart_view.dart' show VedicChartGeometry, vedicPlanetMarker;
import 'vimshottari.dart';

/// Bundled fonts: Inter carries the degree/prime/arrow signs, Poppins adds
/// Devanagari for names. Nothing is downloaded while printing.
class AstrologyPdfFonts {
  const AstrologyPdfFonts({
    required this.base,
    required this.bold,
    this.fallback = const [],
  });

  final pw.Font base;
  final pw.Font bold;
  final List<pw.Font> fallback;

  static Future<AstrologyPdfFonts> load() async {
    Future<pw.Font> font(String asset) async =>
        pw.Font.ttf(await rootBundle.load(asset));
    final inter = await font('assets/google_fonts/Inter/Inter-Variable.ttf');
    final poppins =
        await font('assets/google_fonts/Poppins/Poppins-Regular.ttf');
    final bold = await font('assets/google_fonts/Poppins/Poppins-SemiBold.ttf');
    return AstrologyPdfFonts(
      base: inter,
      bold: bold,
      fallback: [inter, poppins],
    );
  }
}

// Warm, print-friendly inks (the app's paper palette, not screen colors).
final _ink = PdfColor.fromInt(0xFF2B2824);
final _muted = PdfColor.fromInt(0xFF6E665B);
final _accent = PdfColor.fromInt(0xFF8A5A1F);
final _line = PdfColor.fromInt(0xFFD8CFC0);
final _fill = PdfColor.fromInt(0xFFF6F1E7);

const _divisions = [1, 2, 3, 4, 7, 9, 10, 12, 30];

/// A complete, self-contained report of [chart]: birth data, D-1/D-9 charts,
/// panchanga, positions, special lagnas and points, vargas, Vimshottari,
/// Shadbala and Ashtakavarga. Pure layout: every value comes from [chart].
Future<Uint8List> buildAstrologyPdf({
  required AstrologyChart chart,
  required AstrologyPdfFonts fonts,
  DateTime? generatedAt,
}) {
  final input = chart.input;
  final created = (generatedAt ?? DateTime.now()).toUtc();
  final name = input.name.trim().isEmpty ? 'Horoscope' : input.name.trim();
  final base = pw.ThemeData.withFont(
    base: fonts.base,
    bold: fonts.bold,
    fontFallback: fonts.fallback,
  );
  final theme = base.copyWith(
    defaultTextStyle: base.defaultTextStyle.copyWith(
      fontSize: 8.5,
      color: _ink,
    ),
  );
  final document = pw.Document(
    title: '$name · Vedic horoscope',
    author: 'AppFlowy',
    creator: 'AppFlowy Vedic astrology',
    subject: 'Vedic horoscope',
  );
  final report = _Report(chart, created);
  document.addPage(
    pw.MultiPage(
      pageTheme: pw.PageTheme(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.fromLTRB(34, 30, 34, 34),
        theme: theme,
      ),
      maxPages: 40,
      footer: (context) => pw.Container(
        margin: const pw.EdgeInsets.only(top: 8),
        child: pw.Row(
          children: [
            pw.Expanded(
              child: pw.Text(
                '$name · ${input.ayanamsaLabel} · '
                'Swiss Ephemeris ${chart.ephemerisVersion.isEmpty ? '' : chart.ephemerisVersion} '
                '· generated by AppFlowy',
                style: pw.TextStyle(fontSize: 7, color: _muted),
              ),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: pw.TextStyle(fontSize: 7, color: _muted),
            ),
          ],
        ),
      ),
      build: (_) => report.build(name),
    ),
  );
  return document.save();
}

class _Report {
  _Report(this.chart, this.created)
      : input = chart.input,
        lagnaSign = zodiacSign(chart.ascendant),
        periods = vimshottariPeriods(
          birthUtc: chart.utc,
          moonLongitude: chart.planet(VedicBody.moon).longitude,
          yearDays: chart.input.dashaYearDays,
        );

  final AstrologyChart chart;
  final DateTime created;
  final AstrologyInput input;
  final int lagnaSign;
  final List<DashaPeriod> periods;

  List<pw.Widget> build(String name) => [
        pw.Text(
          name,
          style: pw.TextStyle(
            fontSize: 20,
            fontWeight: pw.FontWeight.bold,
            color: _ink,
          ),
        ),
        pw.Text(
          'Vedic horoscope · ${input.style.label} charts · '
          'report generated ${astrologyLocalDate(input, created)}',
          style: pw.TextStyle(fontSize: 9, color: _muted),
        ),
        pw.SizedBox(height: 10),
        _facts(_birthFacts()),
        pw.SizedBox(height: 12),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceEvenly,
          children: [
            _chart('Rasi · D-1', 1),
            _chart('Navamsha · D-9', 9),
          ],
        ),
        _heading('Panchanga at birth'),
        _facts(_panchangaFacts()),
        _heading('Planetary positions'),
        _positions(),
        _note(
          'Houses are whole signs from the Lagna. R = retrograde. Speeds are '
          'sidereal degrees per day. Chara karakas use the 7-karaka scheme '
          '(Sun–Saturn).',
        ),
        _heading('Special lagnas and points'),
        _specialPoints(),
        _note(
          'Bhava, Hora and Ghati lagnas and Gulika/Maandi follow sunrise at the '
          'birthplace; Sri Lagna uses the Moon’s nakshatra fraction. Dhuma, '
          'Vyatipata, Parivesha, Indrachapa and Upaketu are the Sun-based '
          'aprakasha grahas of Parashara.',
        ),
        _heading('Divisional chart signs'),
        _vargas(),
        _heading('Vimshottari dasha'),
        ..._dasha(),
        _heading('Shadbala'),
        ..._shadbala(),
        _heading('Ashtakavarga'),
        _ashtakavarga(),
        _note(
          'Bhinnashtakavarga bindus by sign for each graha and the Lagna. '
          'Sarvashtakavarga totals the seven grahas (Lagna excluded).',
        ),
      ];

  String _moment(DateTime utc, {bool seconds = true}) =>
      '${astrologyLocalDate(input, utc)} '
      '${astrologyLocalClock(input, utc, seconds: seconds)}';

  String _date(DateTime utc) => astrologyLocalDate(input, utc);

  String _dms(double value, String positive, String negative) {
    final seconds = (value.abs() * 3600).round();
    return '${seconds ~/ 3600}°${_two(seconds ~/ 60 % 60)}′'
        '${_two(seconds % 60)}″ ${value < 0 ? negative : positive}';
  }

  List<(String, String)> _birthFacts() {
    final place = input.place;
    final offset = AstrologyTime.offsetAt(input, chart.utc);
    final local = AstrologyTime.localTime(input, chart.utc);
    final zone = place?.timeZone ?? '';
    String? solar(DateTime? time) =>
        time == null ? null : astrologyLocalClock(input, time, seconds: true);
    return [
      (
        'Birth date',
        '${_date(chart.utc)} · ${weekdayNames[local.weekday % 7]}',
      ),
      (
        'Birth time',
        '${astrologyLocalClock(input, chart.utc, seconds: true)} '
            '(${astrologyOffsetLabel(offset)})',
      ),
      (
        'Universal time',
        '${chart.utc.toIso8601String().substring(0, 19).replaceFirst('T', ' ')} UTC',
      ),
      ('Place', place == null || place.name.isEmpty ? '—' : place.name),
      (
        'Coordinates',
        place == null
            ? '—'
            : '${_dms(place.latitude, 'N', 'S')} · '
                '${_dms(place.longitude, 'E', 'W')}',
      ),
      (
        'Time zone',
        input.utcOffsetMinutes != null
            ? 'Fixed offset ${astrologyOffsetLabel(offset)}'
            : zone.isEmpty
                ? 'Device time zone'
                : zone,
      ),
      (
        'Ayanamsha',
        '${input.ayanamsaLabel} · '
            '${_dms(chart.ayanamsaDegrees, '', '−').trim()}',
      ),
      ('Rahu / Ketu', input.trueNode ? 'True node' : 'Mean node'),
      ('Dasha year', '${input.dashaYearDays} days'),
      (
        'Sunrise / sunset',
        solar(chart.sunrise) == null
            ? 'Unavailable (polar day or night)'
            : '${solar(chart.sunrise)} / ${solar(chart.sunset)}',
      ),
      ('Julian day (UT)', chart.julianDay.toStringAsFixed(6)),
      (
        'Ephemeris',
        chart.ephemerisVersion.isEmpty
            ? 'Swiss Ephemeris'
            : 'Swiss Ephemeris ${chart.ephemerisVersion}',
      ),
    ];
  }

  List<(String, String)> _panchangaFacts() {
    final moon = chart.planet(VedicBody.moon);
    final sun = chart.planet(VedicBody.sun);
    final nakshatra = nakshatraIndex(moon.longitude);
    final halfTithi = (chart.elongation / 6).floor();
    final first = periods.first;
    final balance = first.end.difference(chart.utc).inMicroseconds /
        (input.dashaYearDays * Duration.microsecondsPerDay);
    final hora = horaAt(chart);
    return [
      (
        'Vara',
        '${weekdayNames[chart.weekday]} (lord '
            '${weekdayLords[chart.weekday].label})'
            '${chart.sunrise == null ? ' · civil weekday' : ''}',
      ),
      (
        'Tithi',
        '${pakshaName(chart.tithi)} ${tithiName(chart.tithi)} '
            '(${chart.tithi}/30) · '
            '${(chart.tithiRemaining * 100).toStringAsFixed(1)}% remaining',
      ),
      (
        'Nakshatra',
        '${nakshatraNames[nakshatra]} pada ${moon.pada} · lord '
            '${nakshatraLord(nakshatra).label}',
      ),
      ('Yoga', '${yogaNames[chart.yoga]} (${chart.yoga + 1}/27)'),
      ('Karana', karanaName(halfTithi)),
      (
        'Hora lord',
        hora == null
            ? 'Unavailable'
            : '${hora.lord.label} (hora ${hora.number})',
      ),
      (
        'Lagna',
        '${zodiacNames[lagnaSign]} · ${formatZodiacLongitude(chart.ascendant)}',
      ),
      (
        'Moon sign',
        '${zodiacNames[moon.sign]} · lord ${signLords[moon.sign].label}'
      ),
      ('Sun sign', zodiacNames[sun.sign]),
      (
        'Dasha balance',
        '${first.lord.label} · ${balance.toStringAsFixed(4)} years '
            '(${_date(first.end)})',
      ),
    ];
  }

  pw.Widget _heading(String text) => pw.Container(
        margin: const pw.EdgeInsets.only(top: 14, bottom: 5),
        padding: const pw.EdgeInsets.only(bottom: 2),
        decoration: pw.BoxDecoration(
          border: pw.Border(bottom: pw.BorderSide(color: _accent, width: 0.8)),
        ),
        child: pw.Text(
          text,
          style: pw.TextStyle(
            fontSize: 11.5,
            fontWeight: pw.FontWeight.bold,
            color: _accent,
          ),
        ),
      );

  pw.Widget _note(String text) => pw.Padding(
        padding: const pw.EdgeInsets.only(top: 3),
        child: pw.Text(text, style: pw.TextStyle(fontSize: 7, color: _muted)),
      );

  pw.Widget _facts(List<(String, String)> facts) {
    final rows = <pw.TableRow>[];
    for (var i = 0; i < facts.length; i += 2) {
      final pair = [facts[i], if (i + 1 < facts.length) facts[i + 1]];
      rows.add(
        pw.TableRow(
          children: [
            for (final fact in pair) ...[
              _cell(fact.$1, color: _muted),
              _cell(fact.$2),
            ],
            if (pair.length == 1) ...[pw.SizedBox(), pw.SizedBox()],
          ],
        ),
      );
    }
    return pw.Table(
      border: pw.TableBorder(
        horizontalInside: pw.BorderSide(color: _line, width: 0.5),
        top: pw.BorderSide(color: _line, width: 0.5),
        bottom: pw.BorderSide(color: _line, width: 0.5),
      ),
      columnWidths: const {
        0: pw.FlexColumnWidth(1.1),
        1: pw.FlexColumnWidth(2.2),
        2: pw.FlexColumnWidth(1.1),
        3: pw.FlexColumnWidth(2.2),
      },
      children: rows,
    );
  }

  pw.Widget _cell(String text, {PdfColor? color}) => pw.Padding(
        padding: const pw.EdgeInsets.symmetric(horizontal: 3, vertical: 2.5),
        child: pw.Text(text, style: pw.TextStyle(color: color ?? _ink)),
      );

  pw.Widget _table(
    List<String> headers,
    List<List<String>> rows, {
    Map<int, pw.TableColumnWidth>? widths,
    Set<int> numeric = const {},
    double fontSize = 8,
  }) =>
      pw.TableHelper.fromTextArray(
        headers: headers,
        data: rows,
        border: pw.TableBorder.all(color: _line, width: 0.5),
        headerDecoration: pw.BoxDecoration(color: _fill),
        headerStyle: pw.TextStyle(
          fontSize: fontSize,
          fontWeight: pw.FontWeight.bold,
          color: _ink,
        ),
        cellStyle: pw.TextStyle(fontSize: fontSize, color: _ink),
        headerAlignment: pw.Alignment.centerLeft,
        cellAlignment: pw.Alignment.centerLeft,
        headerAlignments: {
          for (final index in numeric) index: pw.Alignment.centerRight,
        },
        cellAlignments: {
          for (final index in numeric) index: pw.Alignment.centerRight,
        },
        cellPadding: const pw.EdgeInsets.symmetric(horizontal: 3, vertical: 2),
        headerPadding:
            const pw.EdgeInsets.symmetric(horizontal: 3, vertical: 2.5),
        columnWidths: widths,
      );

  int _house(double longitude) =>
      houseFromSign(lagnaSign, zodiacSign(longitude));

  pw.Widget _positions() {
    final karakas = calculateJaiminiKarakas(chart.planets);
    List<String> row(VedicPlacement placement, {String karaka = ''}) => [
          '${placement.name}${placement.retrograde ? ' (R)' : ''}',
          formatZodiacLongitude(placement.longitude),
          zodiacNames[placement.sign],
          '${placement.nakshatra} ${placement.pada}',
          nakshatraLord(nakshatraIndex(placement.longitude)).label,
          '${_house(placement.longitude)}',
          zodiacShortNames[divisionalSign(placement.longitude, 9)],
          placement.body == null ? '' : placement.speed.toStringAsFixed(4),
          karaka,
        ];
    return _table(
      [
        'Graha',
        'Longitude',
        'Sign',
        'Nakshatra pada',
        'Nak. lord',
        'House',
        'D-9',
        '°/day',
        'Karaka',
      ],
      [
        row(chart.lagna),
        for (final planet in chart.planets)
          row(
            planet,
            karaka: karakas.forBody(planet.body)?.abbreviation ?? '',
          ),
      ],
      widths: const {
        0: pw.FlexColumnWidth(1.4),
        1: pw.FlexColumnWidth(1.4),
        2: pw.FlexColumnWidth(1.1),
        3: pw.FlexColumnWidth(1.7),
        4: pw.FlexColumnWidth(),
        5: pw.FlexColumnWidth(0.6),
        6: pw.FlexColumnWidth(0.5),
        7: pw.FlexColumnWidth(0.9),
        8: pw.FlexColumnWidth(0.8),
      },
      numeric: const {5, 7},
    );
  }

  pw.Widget _specialPoints() {
    final points = [
      ...chart.specialLagnas,
      ...sunUpagrahas(chart.planet(VedicBody.sun).longitude),
    ];
    return _table(
      ['Point', 'Longitude', 'Sign', 'Nakshatra pada', 'Nak. lord', 'House'],
      [
        for (final point in points)
          [
            '${point.name} (${point.shortName})',
            formatZodiacLongitude(point.longitude),
            zodiacNames[point.sign],
            '${point.nakshatra} ${point.pada}',
            nakshatraLord(nakshatraIndex(point.longitude)).label,
            '${_house(point.longitude)}',
          ],
      ],
      widths: const {
        0: pw.FlexColumnWidth(1.8),
        1: pw.FlexColumnWidth(1.4),
        2: pw.FlexColumnWidth(1.1),
        3: pw.FlexColumnWidth(1.7),
        4: pw.FlexColumnWidth(),
        5: pw.FlexColumnWidth(0.6),
      },
      numeric: const {5},
    );
  }

  pw.Widget _vargas() => _table(
        ['Graha', for (final division in _divisions) 'D-$division'],
        [
          for (final placement in [chart.lagna, ...chart.planets])
            [
              placement.name,
              for (final division in _divisions)
                zodiacShortNames[divisionalSign(placement.longitude, division)],
            ],
        ],
        widths: const {0: pw.FlexColumnWidth(1.6)},
      );

  String _years(Duration duration) => (duration.inMicroseconds /
          (input.dashaYearDays * Duration.microsecondsPerDay))
      .toStringAsFixed(2);

  List<pw.Widget> _dasha() {
    final current = dashaAt(periods, created);
    return [
      if (current.isNotEmpty)
        pw.Padding(
          padding: const pw.EdgeInsets.only(bottom: 5),
          child: pw.Text(
            'Running on ${_date(created)}: '
            '${current.map((period) => period.lord.label).join(' › ')} '
            '(Sookshma ends ${_moment(current.last.end, seconds: false)})',
          ),
        ),
      _table(
        ['Mahadasha', 'Start', 'End', 'Years', 'Age at start'],
        [
          for (final period in periods)
            [
              period.lord.label,
              _date(period.start),
              _date(period.end),
              _years(period.end.difference(period.start)),
              period.start.isBefore(chart.utc)
                  ? 'before birth'
                  : _years(period.start.difference(chart.utc)),
            ],
        ],
        numeric: const {3, 4},
      ),
      pw.SizedBox(height: 8),
      pw.Text(
        'Antardashas',
        style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
      ),
      pw.SizedBox(height: 4),
      pw.Wrap(
        spacing: 8,
        runSpacing: 8,
        children: [
          for (final period in periods)
            pw.SizedBox(
              width: 170,
              child: _table(
                ['${period.lord.label} MD › AD', 'Start', 'End'],
                [
                  for (final child in period.children)
                    [child.lord.label, _date(child.start), _date(child.end)],
                ],
                fontSize: 7,
                widths: const {
                  0: pw.FlexColumnWidth(1.5),
                  1: pw.FlexColumnWidth(1.2),
                  2: pw.FlexColumnWidth(1.2),
                },
              ),
            ),
        ],
      ),
      _note(
        'Dates are in the birth time zone. Periods use a '
        '${input.dashaYearDays}-day year and start from the Moon’s nakshatra '
        'balance at birth.',
      ),
    ];
  }

  List<pw.Widget> _shadbala() {
    final rows = calculateShadbala(chart);
    String value(double? number, {int digits = 2}) =>
        number == null || !number.isFinite
            ? '—'
            : number.toStringAsFixed(digits);
    return [
      _table(
        [
          'Graha',
          'Sthana',
          'Dig',
          'Kala',
          'Cheshta',
          'Naisargika',
          'Drik',
          'Total',
          'Rupas',
          'Req. rupas',
          'Ratio',
        ],
        [
          for (final row in rows)
            [
              row.body.label,
              value(row.sthana),
              value(row.dig),
              value(row.kala),
              value(row.cheshta),
              value(row.naisargika),
              value(row.drik),
              value(row.total),
              value(row.rupas),
              value(row.required / 60),
              value(row.ratio, digits: 3),
            ],
        ],
        numeric: const {1, 2, 3, 4, 5, 6, 7, 8, 9, 10},
        widths: const {0: pw.FlexColumnWidth(1.3)},
      ),
      _note('$shadbalaMethod. $shadbalaMethodDetails'),
    ];
  }

  pw.Widget _ashtakavarga() {
    final result = calculateAshtakavarga(chart);
    int sum(Iterable<int> values) => values.fold(0, (a, b) => a + b);
    List<String> row(String label, List<int> bindus) => [
          label,
          for (final value in bindus) '$value',
          '${sum(bindus)}',
        ];
    return _table(
      ['BAV', ...zodiacShortNames, 'Total'],
      [
        for (var subject = 0; subject < 7; subject++)
          row(VedicBody.classical[subject].label, result.bhinna[subject]),
        row('Lagna', result.bhinna[7]),
        row('SAV', result.sarva),
      ],
      numeric: {for (var i = 1; i <= 13; i++) i},
      widths: const {0: pw.FlexColumnWidth(1.6)},
    );
  }

  pw.Widget _chart(String title, int division) {
    const size = 238.0;
    final ascendant = divisionalSign(chart.ascendant, division);
    final geometry =
        VedicChartGeometry(style: input.style, ascendantSign: ascendant);
    final markers = <int, List<String>>{
      ascendant: ['As'],
    };
    for (final planet in chart.planets) {
      final sign = divisionalSign(planet.longitude, division);
      final degree = (normalizeDegrees(planet.longitude) % 30).floor();
      markers.putIfAbsent(sign, () => []).add(
            division == 1
                ? '${vedicPlanetMarker(planet)} $degree°'
                : vedicPlanetMarker(planet),
          );
    }
    final south = input.style == IndianChartStyle.south;
    return pw.Column(
      children: [
        if (!south)
          pw.Padding(
            padding: const pw.EdgeInsets.only(bottom: 4),
            child: pw.Text(
              title,
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
            ),
          ),
        pw.SizedBox(
          width: size,
          height: size,
          child: pw.Stack(
            children: [
              pw.CustomPaint(
                size: const PdfPoint(size, size),
                painter: (canvas, box) {
                  canvas
                    ..setStrokeColor(_muted)
                    ..setLineWidth(0.6);
                  for (final cell in geometry.cells) {
                    final points = cell.vertices;
                    canvas.moveTo(
                      points.first.dx * box.x,
                      box.y - points.first.dy * box.y,
                    );
                    for (final point in points.skip(1)) {
                      canvas.lineTo(point.dx * box.x, box.y - point.dy * box.y);
                    }
                    canvas.closePath();
                  }
                  canvas.strokePath();
                  canvas
                    ..setStrokeColor(_ink)
                    ..setLineWidth(1)
                    ..drawRect(0, 0, box.x, box.y)
                    ..strokePath();
                },
              ),
              for (final cell in geometry.cells)
                pw.Positioned(
                  left: cell.labelBounds.left * size,
                  top: cell.labelBounds.top * size,
                  child: pw.SizedBox(
                    width: cell.labelBounds.width * size,
                    height: cell.labelBounds.height * size,
                    child: pw.Center(
                      child: pw.FittedBox(
                        fit: pw.BoxFit.scaleDown,
                        child: pw.RichText(
                          textAlign: pw.TextAlign.center,
                          text: pw.TextSpan(
                            children: [
                              pw.TextSpan(
                                text: south
                                    ? zodiacShortNames[cell.sign]
                                    : '${cell.sign + 1}',
                                style: pw.TextStyle(
                                  fontSize: 6.5,
                                  color: _muted,
                                ),
                              ),
                              for (final marker in markers[cell.sign] ?? [])
                                pw.TextSpan(
                                  text: '\n$marker',
                                  style: pw.TextStyle(
                                    fontSize: 8,
                                    color: marker == 'As' ? _accent : _ink,
                                    fontWeight: marker == 'As'
                                        ? pw.FontWeight.bold
                                        : pw.FontWeight.normal,
                                  ),
                                ),
                            ],
                          ),
                        ),
                      ),
                    ),
                  ),
                ),
              if (south)
                pw.Positioned(
                  left: size * 0.25,
                  top: size * 0.25,
                  child: pw.SizedBox(
                    width: size * 0.5,
                    height: size * 0.5,
                    child: pw.Center(
                      child: pw.Column(
                        mainAxisSize: pw.MainAxisSize.min,
                        children: [
                          pw.Text(
                            title,
                            style: pw.TextStyle(
                              fontWeight: pw.FontWeight.bold,
                              color: _accent,
                            ),
                          ),
                          pw.Text(
                            '${zodiacNames[ascendant]} rising',
                            style: pw.TextStyle(fontSize: 7, color: _muted),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
            ],
          ),
        ),
      ],
    );
  }
}

String _two(int value) => value.toString().padLeft(2, '0');
