import 'package:appflowy/extensions/dart/built_in/astrology/astrology_model.dart';
import 'package:appflowy/extensions/dart/built_in/astrology/astrology_style.dart';
import 'package:appflowy/extensions/dart/built_in/astrology/astrology_tables.dart';
import 'package:appflowy/extensions/dart/built_in/astrology/jaimini_karakas.dart';
import 'package:appflowy/shared/paper_theme.dart';
import 'package:appflowy/workspace/application/settings/appearance/base_appearance.dart';
import 'package:appflowy/workspace/application/settings/appearance/desktop_appearance.dart';
import 'package:flowy_infra/theme.dart';
import 'package:flutter/material.dart';
import 'package:flutter_test/flutter_test.dart';

// Hand-authored readings, not expectations generated by the calculator.
// No engine, ephemeris, geolocation or backend setup is needed by these views.
const _seven = [
  (VedicBody.sun, JaiminiKaraka.atma, 28.0),
  (VedicBody.mercury, JaiminiKaraka.amatya, 25.0),
  (VedicBody.moon, JaiminiKaraka.bhratri, 20.0),
  (VedicBody.jupiter, JaiminiKaraka.matri, 15.0),
  (VedicBody.mars, JaiminiKaraka.putra, 12.0),
  (VedicBody.saturn, JaiminiKaraka.gnati, 8.0),
  (VedicBody.venus, JaiminiKaraka.dara, 3.0),
];
const _eight = [
  (VedicBody.sun, JaiminiKaraka.atma, 28.0),
  (VedicBody.mercury, JaiminiKaraka.amatya, 25.0),
  (VedicBody.rahu, JaiminiKaraka.bhratri, 24.0),
  (VedicBody.moon, JaiminiKaraka.matri, 20.0),
  (VedicBody.jupiter, JaiminiKaraka.pitri, 15.0),
  (VedicBody.mars, JaiminiKaraka.putra, 12.0),
  (VedicBody.saturn, JaiminiKaraka.gnati, 8.0),
  (VedicBody.venus, JaiminiKaraka.dara, 3.0),
];
const _readings = {
  JaiminiKarakaScheme.seven: _seven,
  JaiminiKarakaScheme.eight: _eight,
};
const _schemeLabels = {
  JaiminiKarakaScheme.seven: '7 karakas · Sun–Saturn',
  JaiminiKarakaScheme.eight: '8 karakas · including Rahu',
};
const _roleText = {
  JaiminiKaraka.atma: ('AK', 'Atmakaraka', 'Self / soul'),
  JaiminiKaraka.amatya: ('AmK', 'Amatyakaraka', 'Counsel / vocation'),
  JaiminiKaraka.bhratri: ('BK', 'Bhratrikaraka', 'Siblings / courage'),
  JaiminiKaraka.matri: ('MK', 'Matrikaraka', 'Mother / nurture'),
  JaiminiKaraka.pitri: ('PiK', 'Pitrikaraka', 'Father / lineage'),
  JaiminiKaraka.putra: ('PK', 'Putrakaraka', 'Children / creativity'),
  JaiminiKaraka.gnati: ('GK', 'Gnatikaraka', 'Kin / challenges'),
  JaiminiKaraka.dara: ('DK', 'Darakaraka', 'Spouse / partnership'),
};

// Deliberately shuffled and spread across signs. Rahu is at 6°, not the
// separate 5° fixture that would tie Mercury's 25° ranking degree.
const _longitudes = {
  VedicBody.saturn: 158.0,
  VedicBody.rahu: 66.0,
  VedicBody.moon: 110.0,
  VedicBody.venus: 243.0,
  VedicBody.sun: 28.0,
  VedicBody.ketu: 246.0,
  VedicBody.jupiter: 315.0,
  VedicBody.mercury: 55.0,
  VedicBody.mars: 192.0,
};
const _points = [
  VedicPlacement(name: 'Bhava Lagna', shortName: 'BL', longitude: 45.125),
  VedicPlacement(name: 'Hora Lagna', shortName: 'HL', longitude: 93.25),
];

void main() {
  group('calculateJaiminiKarakas', () {
    test('schemes expose ordered roles, with Pitri only in eight', () {
      expect(JaiminiKarakaScheme.values, _schemeLabels.keys);
      expect(JaiminiKaraka.values, _roleText.keys);
      for (final entry in _readings.entries) {
        expect(entry.key.label, _schemeLabels[entry.key]);
        expect(entry.key.karakas, entry.value.map((row) => row.$2));
      }
      for (final entry in _roleText.entries) {
        expect(entry.key.abbreviation, entry.value.$1);
        expect(entry.key.label, entry.value.$2);
        expect(entry.key.signification, entry.value.$3);
      }
    });

    test('defaults to seven and ranks a lazy iterable within each sign', () {
      final result = calculateJaiminiKarakas(_placements().map((p) => p));
      expect(result.scheme, JaiminiKarakaScheme.seven);
      _expectCalculation(result, _seven);
      expect(result.forBody(VedicBody.rahu), isNull);
    });

    test('eight reverses Rahu at positive speed and includes separate Pitri',
        () {
      final placements = _placements();
      expect(
        placements.singleWhere((p) => p.body == VedicBody.rahu).speed,
        greaterThan(0),
      );
      final result = calculateJaiminiKarakas(
        placements,
        scheme: JaiminiKarakaScheme.eight,
      );
      expect(result.scheme, JaiminiKarakaScheme.eight);
      _expectCalculation(result, _eight);
    });

    test('retrograde or stationary motion never reverses physical ranks', () {
      // Synthetic speeds isolate the ranking rule, not ephemeris behaviour.
      for (final speed in [-0.7, 0.0, 0.7]) {
        final placements = _placements(
          speeds: {for (final body in VedicBody.values) body: speed},
        );
        for (final entry in _readings.entries) {
          _expectCalculation(
            calculateJaiminiKarakas(placements, scheme: entry.key),
            entry.value,
          );
        }
      }
    });

    test('normalizes negative and multiple full turns before ranking', () {
      final placements = _placements(
        longitudes: {
          VedicBody.sun: -332,
          VedicBody.moon: 830,
          VedicBody.mars: -528,
          VedicBody.mercury: 1495,
          VedicBody.jupiter: -765,
          VedicBody.venus: 1323,
          VedicBody.saturn: -922,
          VedicBody.rahu: 1146,
        },
      );
      for (final entry in _readings.entries) {
        _expectCalculation(
          calculateJaiminiKarakas(placements, scheme: entry.key),
          entry.value,
        );
      }
    });

    test('a sign cusp ranks Rahu at 30 degrees but a physical planet at zero',
        () {
      for (final longitude in [0.0, 30.0, 270.0, -360.0, 1080.0]) {
        final result = calculateJaiminiKarakas(
          _placements(longitudes: {VedicBody.rahu: longitude}),
          scheme: JaiminiKarakaScheme.eight,
        );
        expect(result.assignments.first.placement.body, VedicBody.rahu);
        expect(result.forBody(VedicBody.rahu)!.rankDegrees, 30);
        expect(result.forBody(VedicBody.rahu)!.karakas, [JaiminiKaraka.atma]);
        expect(result.forBody(VedicBody.sun)!.karakas, [JaiminiKaraka.amatya]);
        expect(result.hasTies, isFalse);
      }
      final sun = calculateJaiminiKarakas(
        _placements(longitudes: {VedicBody.sun: 0}),
      ).forBody(VedicBody.sun)!;
      expect(sun.rankDegrees, 0);
      expect(sun.karakas, [JaiminiKaraka.dara]);
    });

    test('keeps sub-second precision even when both displayed degrees match',
        () {
      final result = calculateJaiminiKarakas(
        _placements(
          longitudes: {
            VedicBody.sun: 28.000000001,
            VedicBody.mercury: 28.000000002,
          },
        ),
      );
      final sun = result.forBody(VedicBody.sun)!;
      final mercury = result.forBody(VedicBody.mercury)!;
      expect(sun.placement.formatted, '28° Ar 00′ 00″');
      expect(mercury.placement.formatted, sun.placement.formatted);
      expect(
        mercury.rankDegrees.toStringAsFixed(8),
        sun.rankDegrees.toStringAsFixed(8),
      );
      expect(sun.rankDegrees, 28.000000001);
      expect(mercury.rankDegrees, 28.000000002);
      expect(mercury.karakas, [JaiminiKaraka.atma]);
      expect(sun.karakas, [JaiminiKaraka.amatya]);
      expect(result.hasTies, isFalse);
    });

    test('Mercury and Rahu share affected roles, with stable exact-tie display',
        () {
      final placements = _placements(longitudes: {VedicBody.rahu: 65});
      for (final input in [placements, placements.reversed]) {
        final result = calculateJaiminiKarakas(
          input,
          scheme: JaiminiKarakaScheme.eight,
        );
        expect(result.hasTies, isTrue);
        expect(result.assignments.map((a) => a.placement.body), [
          VedicBody.sun,
          VedicBody.mercury,
          VedicBody.rahu,
          VedicBody.moon,
          VedicBody.jupiter,
          VedicBody.mars,
          VedicBody.saturn,
          VedicBody.venus,
        ]);
        for (final body in [VedicBody.mercury, VedicBody.rahu]) {
          final assignment = result.forBody(body)!;
          expect(assignment.rankDegrees, 25);
          expect(assignment.karakas,
              [JaiminiKaraka.amatya, JaiminiKaraka.bhratri]);
          expect(assignment.isTied, isTrue);
          expect(assignment.abbreviation, 'AmK / BK (tie)');
        }
        expect(result.forBody(VedicBody.sun)!.karakas, [JaiminiKaraka.atma]);
        expect(result.forBody(VedicBody.moon)!.karakas, [JaiminiKaraka.matri]);
        expect(
            result.forBody(VedicBody.jupiter)!.karakas, [JaiminiKaraka.pitri]);
      }
    });

    test('ties include the 1e-10 boundary but not larger differences', () {
      // Near zero, the boundary subtraction is not rounded at a large angle.
      for (final sample in const [
        (0.0, true),
        (5e-11, true),
        (1e-10, true),
        (2e-10, false),
      ]) {
        final result = calculateJaiminiKarakas(
          _placements(
              longitudes: {VedicBody.sun: 0, VedicBody.mercury: sample.$1}),
        );
        expect(result.hasTies, sample.$2, reason: 'Gap ${sample.$1}');
        for (final body in [VedicBody.sun, VedicBody.mercury]) {
          final assignment = result.forBody(body)!;
          expect(assignment.isTied, sample.$2);
          final role =
              body == VedicBody.sun ? JaiminiKaraka.dara : JaiminiKaraka.gnati;
          expect(
            assignment.karakas,
            sample.$2 ? [JaiminiKaraka.gnati, JaiminiKaraka.dara] : [role],
          );
          expect(
            assignment.abbreviation,
            sample.$2 ? 'GK / DK (tie)' : _roleText[role]!.$1,
          );
        }
      }
    });

    test('a three-way middle tie shares the entire role range', () {
      final result = calculateJaiminiKarakas(
        _placements(
          longitudes: {VedicBody.mercury: 50, VedicBody.jupiter: 320},
        ).reversed,
      );
      expect(result.hasTies, isTrue);
      expect(
        result.assignments.where((a) => a.isTied).map((a) => a.placement.body),
        [VedicBody.moon, VedicBody.mercury, VedicBody.jupiter],
      );
      for (final body in [
        VedicBody.moon,
        VedicBody.mercury,
        VedicBody.jupiter
      ]) {
        final assignment = result.forBody(body)!;
        expect(assignment.rankDegrees, 20);
        expect(assignment.karakas, [
          JaiminiKaraka.amatya,
          JaiminiKaraka.bhratri,
          JaiminiKaraka.matri,
        ]);
        expect(assignment.abbreviation, 'AmK / BK / MK (tie)');
      }
      expect(result.forBody(VedicBody.mars)!.karakas, [JaiminiKaraka.putra]);
    });

    test('each missing required planet throws FormatException', () {
      expect(() => calculateJaiminiKarakas(const []), throwsFormatException);
      for (final entry in _readings.entries) {
        for (final row in entry.value) {
          expect(
            () => calculateJaiminiKarakas(
              _placements().where((p) => p.body != row.$1),
              scheme: entry.key,
            ),
            throwsFormatException,
            reason: '${entry.key.name}: missing ${row.$1.name}',
          );
        }
      }
    });

    test('duplicate required bodies are rejected even at different longitudes',
        () {
      for (final entry in _readings.entries) {
        for (final row in entry.value) {
          expect(
            () => calculateJaiminiKarakas(
              [..._placements(), _placement(row.$1, 1)],
              scheme: entry.key,
            ),
            throwsFormatException,
            reason: '${entry.key.name}: duplicate ${row.$1.name}',
          );
        }
      }
    });

    test('NaN and either infinity are rejected for every required body', () {
      for (final entry in _readings.entries) {
        for (final row in entry.value) {
          for (final value in [
            double.nan,
            double.infinity,
            double.negativeInfinity
          ]) {
            expect(
              () => calculateJaiminiKarakas(
                _placements(longitudes: {row.$1: value}),
                scheme: entry.key,
              ),
              throwsFormatException,
              reason: '${entry.key.name}: ${row.$1.name} at $value',
            );
          }
        }
      }
    });

    test('ignores extra lagnas and Ketu, and ignores Rahu only in seven', () {
      final extras = [
        ..._placements(),
        ..._points,
        _placement(VedicBody.ketu, double.nan),
        _placement(VedicBody.ketu, double.infinity),
        const VedicPlacement(
            name: 'Lagna', shortName: 'As', longitude: double.nan),
        const VedicPlacement(
            name: 'Sun', shortName: 'Su', longitude: double.infinity),
      ];
      _expectCalculation(
        calculateJaiminiKarakas(extras, scheme: JaiminiKarakaScheme.eight),
        _eight,
      );
      _expectCalculation(
        calculateJaiminiKarakas([
          ...extras,
          _placement(VedicBody.rahu, double.nan),
          _placement(VedicBody.rahu, double.negativeInfinity),
        ]),
        _seven,
      );
      _expectCalculation(
        calculateJaiminiKarakas(
          extras.where(
              (p) => p.body != VedicBody.rahu && p.body != VedicBody.ketu),
        ),
        _seven,
      );
    });

    test('results and tied role lists are immutable without mutating input',
        () {
      for (final entry in _readings.entries) {
        final input = _placements(longitudes: {VedicBody.rahu: 65});
        final before = List<VedicPlacement>.of(input);
        final result = calculateJaiminiKarakas(input, scheme: entry.key);
        expect(input, orderedEquals(before));
        expect(
          () => calculateJaiminiKarakas(List.unmodifiable(before),
              scheme: entry.key),
          returnsNormally,
        );
        expect(() => result.assignments.add(result.assignments.first),
            throwsUnsupportedError);
        expect(() => result.assignments[0] = result.assignments.last,
            throwsUnsupportedError);
        for (final assignment in result.assignments) {
          expect(
            assignment.placement,
            same(
                before.singleWhere((p) => p.body == assignment.placement.body)),
          );
          expect(() => assignment.karakas.add(JaiminiKaraka.pitri),
              throwsUnsupportedError);
          expect(() => assignment.karakas[0] = JaiminiKaraka.dara,
              throwsUnsupportedError);
        }
        expect(input, orderedEquals(before));
        input.clear();
        expect(result.assignments, hasLength(entry.value.length));
        expect(result.forBody(VedicBody.sun)!.rankDegrees, 28);
      }
    });
  });

  group('AstrologyPlacementsTable Jaimini readings', () {
    testWidgets(
        'seven/eight readings fit 280/900 in real light, dark and paper themes',
        (tester) async {
      _setViewport(tester);
      final chart = _chart();
      for (final appearance in const [
        (Brightness.light, false),
        (Brightness.dark, false),
        (Brightness.light, true),
      ]) {
        for (final width in [280.0, 900.0]) {
          // Fresh state per layout: selecting eight must not leak into the next case.
          await tester.pumpWidget(const SizedBox.shrink());
          await tester.pumpWidget(
            _app(chart,
                width: width, brightness: appearance.$1, paper: appearance.$2),
          );
          final surface = _key('astrology-placements-surface');
          final context = tester.element(surface);
          final palette = AstrologyPalette.of(context);
          expect(tester.getSize(surface), Size(width, 500));
          expect(Theme.of(context).brightness, appearance.$1);
          expect(PaperTheme.isEnabled(context), appearance.$2);
          expect(tester.widget<ColoredBox>(surface).color, palette.surface);
          if (appearance.$2) {
            expect(palette.surface, PaperTheme.editorPreviewBackground);
          }
          final selector = tester.widget<DropdownButton<JaiminiKarakaScheme>>(
            _key('jaimini-karaka-scheme'),
          );
          expect(selector.value, JaiminiKarakaScheme.seven);
          expect(selector.dropdownColor, palette.raised);
          expect(selector.focusColor, palette.hover);
          expect(_textIn('placements-table', 'Jaimini karaka'), findsOneWidget);
          expect(tester.widget<Table>(_key('placements-table')).children,
              hasLength(13));
          _expectReading(tester, _seven);
          for (final point in ['As', 'Ra', 'Ke', 'BL', 'HL']) {
            expect(_value(tester, 'placements-$point-karaka'), '—');
          }
          expect(_value(tester, 'jaimini-karaka-heading'),
              'Jaimini Karaka details');
          expect(
            tester.getTopLeft(_key('jaimini-karakas-table')).dy,
            greaterThan(tester.getBottomLeft(_key('placements-table')).dy),
          );
          expect(_key('jaimini-karaka-error'), findsNothing);
          expect(_key('jaimini-karaka-tie-warning'), findsNothing);
          final vertical = _controller(tester, 'astrology-placements-scroll');
          final details =
              _controller(tester, 'jaimini-karakas-horizontal-scroll');
          expect(vertical.position.maxScrollExtent, greaterThan(0));
          expect(identical(vertical, details), isFalse);
          expect(
            identical(
                details, _controller(tester, 'placements-horizontal-scroll')),
            isFalse,
          );
          _expectHealthy(tester);
          await _panTable(tester, 'placements-horizontal-scroll');
          await _chooseScheme(tester, JaiminiKarakaScheme.eight);
          _expectReading(tester, _eight);
          expect(_value(tester, 'placements-Ra-karaka'), 'BK');
          expect(_value(tester, 'placements-Ju-karaka'), 'PiK');
          expect(_value(tester, 'placements-Ke-karaka'), '—');
          expect(_value(tester, 'jaimini-karaka-method'),
              contains('Rahu uses 30° minus'));
          if (width == 280) {
            await _panTable(tester, 'jaimini-karakas-horizontal-scroll');
          } else {
            expect(details.position.maxScrollExtent, 0);
          }
          _expectHealthy(tester);
        }
      }
    }, variant: TargetPlatformVariant.only(TargetPlatform.windows));

    testWidgets(
        'a new eight-karaka reading updates rows without resetting the scheme',
        (tester) async {
      _setViewport(tester);
      await tester.pumpWidget(_app(_chart()));
      await _chooseScheme(tester, JaiminiKarakaScheme.eight);
      await tester.pumpWidget(
        _app(
          _chart(
            planets: _placements(
              longitudes: {
                VedicBody.sun: 2,
                VedicBody.venus: 59,
                VedicBody.rahu: 89
              },
            ),
          ),
        ),
      );
      expect(
        tester
            .widget<DropdownButton<JaiminiKarakaScheme>>(
                _key('jaimini-karaka-scheme'))
            .value,
        JaiminiKarakaScheme.eight,
      );
      _expectReading(tester, const [
        (VedicBody.venus, JaiminiKaraka.atma, 29.0),
        (VedicBody.mercury, JaiminiKaraka.amatya, 25.0),
        (VedicBody.moon, JaiminiKaraka.bhratri, 20.0),
        (VedicBody.jupiter, JaiminiKaraka.matri, 15.0),
        (VedicBody.mars, JaiminiKaraka.pitri, 12.0),
        (VedicBody.saturn, JaiminiKaraka.putra, 8.0),
        (VedicBody.sun, JaiminiKaraka.gnati, 2.0),
        (VedicBody.rahu, JaiminiKaraka.dara, 1.0),
      ]);
      await _chooseScheme(tester, JaiminiKarakaScheme.seven);
      expect(_value(tester, 'placements-Ra-karaka'), '—');
      expect(_value(tester, 'placements-Su-karaka'), 'DK');
      expect(_value(tester, 'placements-Ma-karaka'), 'PK');
      expect(_key('jaimini-rahu-role'), findsNothing);
      expect(
          _textIn('jaimini-karakas-table', 'PiK · Pitrikaraka'), findsNothing);
      _expectHealthy(tester);
    }, variant: TargetPlatformVariant.only(TargetPlatform.windows));

    testWidgets(
        'missing planets show a recoverable karaka error, not a broken placements list',
        (tester) async {
      _setViewport(tester);
      final missingSaturn = _chart(
        planets:
            _placements().where((p) => p.body != VedicBody.saturn).toList(),
      );
      await tester.pumpWidget(_app(missingSaturn));
      _expectUnavailable(
          tester, missingSaturn, VedicBody.saturn, JaiminiKarakaScheme.seven);
      await tester.ensureVisible(_key('jaimini-karaka-error'));
      await tester.pumpAndSettle();

      final missingRahu = _chart(
        planets: _placements().where((p) => p.body != VedicBody.rahu).toList(),
      );
      await tester.pumpWidget(_app(missingRahu));
      _expectReading(tester, _seven);
      expect(_key('jaimini-karaka-error'), findsNothing);
      await _chooseScheme(tester, JaiminiKarakaScheme.eight);
      _expectUnavailable(
          tester, missingRahu, VedicBody.rahu, JaiminiKarakaScheme.eight);
      await tester.pumpWidget(_app(_chart()));
      _expectReading(tester, _eight);
      expect(_key('jaimini-karaka-error'), findsNothing);
      _expectHealthy(tester);
    }, variant: TargetPlatformVariant.only(TargetPlatform.windows));

    testWidgets(
        'ties show an unresolved-role note instead of false exact assignments',
        (tester) async {
      _setViewport(tester);
      await tester.pumpWidget(
        _app(_chart(planets: _placements(longitudes: {VedicBody.rahu: 65}))),
      );
      expect(_key('jaimini-karaka-tie-warning'), findsNothing);
      expect(_value(tester, 'placements-Me-karaka'), 'AmK');
      await _chooseScheme(tester, JaiminiKarakaScheme.eight);
      for (final body in [VedicBody.mercury, VedicBody.rahu]) {
        expect(_value(tester, 'placements-${body.shortName}-karaka'),
            'AmK / BK (tie)');
        expect(
          _value(tester, 'jaimini-${body.name}-role'),
          'AmK · Amatyakaraka / BK · Bhratrikaraka (tie)',
        );
        expect(_value(tester, 'jaimini-${body.name}-degree'), '25.00000000°');
      }
      expect(
        _textIn(
            'jaimini-karakas-table', 'Counsel / vocation / Siblings / courage'),
        findsNWidgets(2),
      );
      expect(
          _textIn('jaimini-karakas-table', 'AmK · Amatyakaraka'), findsNothing);
      expect(
          _textIn('jaimini-karakas-table', 'BK · Bhratrikaraka'), findsNothing);
      expect(_value(tester, 'placements-Mo-karaka'), 'MK');
      expect(_value(tester, 'placements-Ju-karaka'), 'PiK');
      expect(tester.widget<Table>(_key('jaimini-karakas-table')).children,
          hasLength(9));
      final note = _value(tester, 'jaimini-karaka-tie-warning');
      expect(note, contains('affected roles are unresolved'));
      expect(note, contains('not arbitrarily assigned'));
      expect(note, contains('No secondary tie-breaking convention'));
      await tester.ensureVisible(_key('jaimini-karaka-tie-warning'));
      await tester.pumpAndSettle();
      _expectHealthy(tester);
      await tester.pumpWidget(_app(_chart()));
      expect(_key('jaimini-karaka-tie-warning'), findsNothing);
      _expectReading(tester, _eight);
      _expectHealthy(tester);
    }, variant: TargetPlatformVariant.only(TargetPlatform.windows));
  });
}

VedicPlacement _placement(VedicBody body, double longitude,
        {double speed = 0.1}) =>
    VedicPlacement(
        name: body.label,
        shortName: body.shortName,
        body: body,
        longitude: longitude,
        speed: speed);

List<VedicPlacement> _placements({
  Map<VedicBody, double> longitudes = const {},
  Map<VedicBody, double> speeds = const {},
}) =>
    [
      for (final entry in _longitudes.entries)
        _placement(entry.key, longitudes[entry.key] ?? entry.value,
            speed: speeds[entry.key] ?? 0.1),
    ];

void _expectCalculation(
  JaiminiKarakaResult result,
  List<(VedicBody, JaiminiKaraka, double)> expected,
) {
  expect(result.hasTies, isFalse);
  expect(result.assignments.map((a) => a.placement.body),
      expected.map((row) => row.$1));
  expect(result.forBody(null), isNull);
  expect(result.forBody(VedicBody.ketu), isNull);
  for (final (body, role, rank) in expected) {
    final assignment = result.forBody(body)!;
    expect(assignment.rankDegrees, rank);
    expect(assignment.karakas, [role]);
    expect(assignment.abbreviation, _roleText[role]!.$1);
    expect(assignment.isTied, isFalse);
  }
}

AstrologyChart _chart({List<VedicPlacement>? planets}) {
  final utc = DateTime.utc(2000, 1, 1, 12);
  return AstrologyChart(
    input: AstrologyInput(
      name: 'Hand-authored Jaimini fixture',
      utc: utc,
      place: const AstrologyPlace(
          name: 'Fixture city', latitude: 0, longitude: 0, timeZone: 'Etc/UTC'),
      utcOffsetMinutes: 0,
    ),
    utc: utc,
    julianDay: 2451545,
    ayanamsaDegrees: 23.85675,
    ascendant: 33,
    midheaven: 303,
    planets: planets ?? _placements(),
    specialLagnas: _points,
    sunrise: DateTime.utc(2000, 1, 1, 6),
    sunset: DateTime.utc(2000, 1, 1, 18),
    nextSunrise: DateTime.utc(2000, 1, 2, 6),
    weekday: 6,
    localMeanHours: 12,
  );
}

Widget _app(
  AstrologyChart chart, {
  double width = 900,
  Brightness brightness = Brightness.light,
  bool paper = false,
}) =>
    MaterialApp(
      themeAnimationDuration: Duration.zero,
      theme: DesktopAppearance().getThemeData(
        paper
            ? AppTheme.builtins
                .firstWhere((theme) => theme.themeName == BuiltInTheme.paper)
            : AppTheme.fallback,
        brightness,
        defaultFontFamily,
        builtInCodeFontFamily,
      ),
      home: Scaffold(
        body: Center(
          child: SizedBox(
            width: width,
            height: 500,
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(child: AstrologyPlacementsTable(chart: chart))
              ],
            ),
          ),
        ),
      ),
    );

void _setViewport(WidgetTester tester) {
  tester.view
    ..devicePixelRatio = 1
    ..physicalSize = const Size(1000, 800);
  addTearDown(tester.view.reset);
}

Finder _key(String key) => find.byKey(ValueKey(key));

String _value(WidgetTester tester, String key) => tester
    .widget<SelectableText>(
      find.descendant(
          of: _key(key),
          matching: find.byType(SelectableText),
          matchRoot: true),
    )
    .data!;

Finder _textIn(String table, String text) => find.descendant(
      of: _key(table),
      matching: find.byWidgetPredicate(
          (widget) => widget is SelectableText && widget.data == text),
    );

void _expectReading(
    WidgetTester tester, List<(VedicBody, JaiminiKaraka, double)> expected) {
  expect(tester.widget<Table>(_key('jaimini-karakas-table')).children,
      hasLength(expected.length + 1));
  // These tables eagerly build clipped cells. Inspect their values without
  // pretending every cell is hit-testable before scrolling it into view.
  for (final (body, role, rank) in expected) {
    final (abbreviation, label, signification) = _roleText[role]!;
    expect(_value(tester, 'placements-${body.shortName}-karaka'), abbreviation);
    expect(
        _value(tester, 'jaimini-${body.name}-role'), '$abbreviation · $label');
    expect(_value(tester, 'jaimini-${body.name}-degree'),
        '${rank.toStringAsFixed(8)}°');
    expect(_textIn('jaimini-karakas-table', '$abbreviation · $label'),
        findsOneWidget);
    expect(_textIn('jaimini-karakas-table', signification), findsOneWidget);
  }
}

ScrollController _controller(WidgetTester tester, String key) =>
    tester.widget<SingleChildScrollView>(_key(key)).controller!;

Future<void> _panTable(WidgetTester tester, String id) async {
  final scroll = tester.widget<SingleChildScrollView>(_key(id));
  expect(scroll.scrollDirection, Axis.horizontal);
  expect(scroll.primary, isFalse);
  final horizontal = scroll.controller!;
  final vertical = _controller(tester, 'astrology-placements-scroll');
  expect(identical(horizontal, vertical), isFalse);
  expect(horizontal.position.maxScrollExtent, greaterThan(0));
  await tester.ensureVisible(_key(id));
  await tester.pumpAndSettle();
  final before = horizontal.offset;
  final verticalBefore = vertical.offset;
  final visible = tester
      .getRect(_key(id))
      .intersect(tester.getRect(_key('astrology-placements-surface')));
  // Header padding avoids SelectableText's selection gesture recognizers.
  await tester.dragFrom(
      visible.topRight + const Offset(-16, 4), const Offset(-160, 0));
  await tester.pumpAndSettle();
  expect(horizontal.offset, greaterThan(before));
  expect(vertical.offset, verticalBefore);
}

Future<void> _chooseScheme(
    WidgetTester tester, JaiminiKarakaScheme scheme) async {
  await tester.ensureVisible(_key('jaimini-karaka-scheme'));
  await tester.pumpAndSettle();
  await tester.tap(_key('jaimini-karaka-scheme'));
  await tester.pumpAndSettle();
  final option = find.text(_schemeLabels[scheme]!).last;
  await tester.ensureVisible(option);
  await tester.pumpAndSettle();
  await tester.tap(option);
  await tester.pumpAndSettle();
  expect(
    tester
        .widget<DropdownButton<JaiminiKarakaScheme>>(
            _key('jaimini-karaka-scheme'))
        .value,
    scheme,
  );
}

void _expectUnavailable(
  WidgetTester tester,
  AstrologyChart chart,
  VedicBody missing,
  JaiminiKarakaScheme scheme,
) {
  expect(_value(tester, 'jaimini-karaka-error'),
      '${missing.label} is missing; Jaimini Karakas are unavailable.');
  expect(_key('placements-${missing.shortName}-name'), findsNothing);
  expect(_key('jaimini-karakas-table'), findsNothing);
  expect(_key('jaimini-karaka-tie-warning'), findsNothing);
  expect(tester.widget<Table>(_key('placements-table')).children,
      hasLength(chart.placements.length + 1));
  for (final placement in chart.placements) {
    final key = 'placements-${placement.shortName}';
    expect(
        _value(tester, '$key-name'), placement.body?.label ?? placement.name);
    expect(_value(tester, '$key-longitude'), placement.formatted);
    final required = _readings[scheme]!.any((row) => row.$1 == placement.body);
    expect(_value(tester, '$key-karaka'), required ? 'Unavailable' : '—');
  }
  _expectHealthy(tester);
}

void _expectHealthy(WidgetTester tester) {
  expect(find.byType(RawScrollbar), findsNothing);
  expect(find.byType(Scrollbar), findsNothing);
  expect(find.byType(ErrorWidget), findsNothing);
  expect(tester.takeException(), isNull);
}
